events {
    worker_connections 1024;
}

http {
    upstream catalog_svc {
        server catalog-service:8080;
    }

    upstream order_svc {
        server order-service:8080;
    }

    upstream delivery_svc {
        server delivery-service:8080;
    }

    server {
        listen 80;

        location /api/v1/restaurants {
            proxy_pass http://catalog_svc;
        }

        location ~ ^/api/v1/orders/.*/status$ {
            proxy_pass http://delivery_svc;
        }

        location /api/v1/orders {
            proxy_pass http://order_svc;
        }

        # WebSocket support for real-time tracking
        location /ws {
            proxy_pass http://delivery_svc;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }
    }
}
